### ISSUE TITLE
Point representation

### ISSUE THREAD

**Issue by BycorSanchez** [arthur-e/Wicket#107]
Hi all!
I have tested Wicket for a while and I have a question about geographical data. Geographic points are treated by Wicket as (Longitude, Latitude). Is there any way to treat them in Wicket as (Latitude, Longitude), the standard ISO 6709?
I can swap every point coordinate parameters, but I want to avoid if possible.
Thanks!

**Comment by arthur-e** [comment]
Hi @BycorSanchez,

Thanks for your question. The WKT standard is Long., Lat.; this maps on to the X, Y ordering of an arbitrary Cartesian coordinate system.

Swapping every point coordinate pair... For mapping applications, this should be pretty easy. You would swap them before mapping? Or swap them after a point is drawn on the map (and internalized as WKT by Wicket)? Either way, JavaScript has a number of options to, e.g., [reverse the order of the coordinates in an array](https://www.google.com/search?q=javascript+reverse+array&rlz=1C5CHFA_enUS569US569&oq=javascript+reverse+array&aqs=chrome..69i57j0l5.3767j0j1&sourceid=chrome&ie=UTF-8).

For some features, I would say, "Sounds interesting. Submit a pull request!" but here I think Wicket does the right thing by honoring the WKT standard, not any other (equally valid) standard.

Arthur

**Comment by BycorSanchez** [comment]
Hi @arthur-e 

Thanks for your answer. I didn't know that WKT standard was Long, Lat. Most of the time I work with geographic representation where the standard is just the opposite. It make sense then that Wicket follow the WKT standard.

Finally I've opted to swap every point coordinate pair before mapping, right after Wicket's parsing, so the point is correctly mapped in gmaps.

Thanks!
