### ISSUE TITLE
Wicket is not working with Leaflet 1.1.0

### ISSUE THREAD

**Issue by dasdany** [arthur-e/Wicket#109]
Wicket is not working anymore with leaflet 1.1.0.
There are some discussions on other projects like Leaflet/Leaflet.draw#739 and leaflet itself Leaflet/Leaflet#5589.
It's not possible anymore to extend leaflet on the old way. So coordsToLatLngs() and coordsToLatLng() are not working.

**Comment by ddproxy** [comment]
Leaflet.Draw 0.4.10 introduces a leaflet restriction to prevent it being installed alongside L 1.1.0. We are working on introducing the changes for Leaflet 1.1.0 but that has not been released yet.

**Comment by dasdany** [comment]
Duplicate of #112
