### ISSUE TITLE
How to send to google.maps.Polygon

### ISSUE THREAD

**Issue by neilm813** [arthur-e/Wicket#116]
Hello and thanks for this tool! I could use a little help please:

I tried following the provided example and am successfully able to log wkt.components and execute wkt.toObject(), but I'm unsure how to proceed and send the object to google.maps.Polygon

I've used google.maps.Polygon before so I only need to know how / where to extract the properly formatted coordinates regardless of wkt polygon type. Thanks.

**Comment by arthur-e** [comment]
Hi @neilm813, it is `toObject()` that gives you an instance of the `google.maps.Polygon` class (or could be said "gives you a `google.maps.Polygon` object"). To get this on a map, let's assume you have a `google.maps.Map` object assigned to a variable `map`.

Every `google.maps.Polygon` has a method called `setMap()` which accepts, as its only argument, the `map`, in this case ([see reference](https://developers.google.com/maps/documentation/javascript/3.exp/reference#Polygon)). So:

```js
// Create a google.maps.Polygon
myPolygon = wkt.toObject()

// Show the polygon on the map
myPolygon.setMap(map)
```

**Comment by neilm813** [comment]
Appreciate the help, thanks @arthur-e
