### ISSUE TITLE
wicket-leaflet deconstruct: Typo for L.Circle

### ISSUE THREAD

**Issue by janu75** [arthur-e/Wicket#130]
Hi

This bug is both in release 1.3.4 and the main repo.
In file wicket-leaflet.js, function Wkt.Wkt.prototype.deconstruct:

 

```
   // L.Circle ////////////////////////////////////////////////////////////////
        if (obj.constructor === L.Rectangle || obj.constructor === L.rectangle) {
console.log('Deconstruction of L.Circle objects is not yet supported');

```

The test is currently checking for constructor L.Rectangle, but obviously this should be L.Circle/L.circle.

**Comment by technicolorenvy** [comment]
Closed by https://github.com/arthur-e/Wicket/pull/131
