### ISSUE TITLE
Cannot read property 'polygon' of undefined

### ISSUE THREAD

**Issue by pjs21s** [arthur-e/Wicket#150]
Hello I'm using Wicket like this (vue : 2.6.11, leaflet : 1.6.0, wicket : 1.3.6)

```javascript
<template>
<l-control>
      <p @click="makePolygon"></p>
      </l-control>
</template>
<script>
import Wkt from 'wicket';

makePolygon() {
      let wkt = new Wkt.Wkt();
      let poly = wkt.read("POLYGON ((126.93191528320311 37.48248679787437, 127.09671020507812 37.48248679787437, 127.09671020507812 37.607704112428394, 126.93191528320311 37.607704112428394, 126.93191528320311 37.48248679787437))").toObject();
console.log(poly);

</script>
}
```

When i click my `makePolygon` event then i can see these error
```
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'polygon' of undefined"
TypeError: Cannot read property 'polygon' of undefined
```

I wrote wrong code or is this bug?
Even i deleted npm module and only used wicket with cdn but i saw same errors
Thank you for reading

**Comment by arthur-e** [comment]
Hi @pjs21s,  it definitely looks like the wrong code in the example you provided. Your closing curly brace `}` is outside of the closing `</script>` tag when it should be inside.

**Comment by pjs21s** [comment]
> Hi @pjs21s, it definitely looks like the wrong code in the example you provided. Your closing curly brace `}` is outside of the closing `</script>` tag when it should be inside.

ah that is my mistake. Even i write </script> tag right way. There is same error

**Comment by pjs21s** [comment]
@arthur-e  that was my mistake. Even i write </script> tag right way. There is same error.
