### ISSUE TITLE
ESRI ArcGIS JavaScript API demo fails

### ISSUE THREAD

**Issue by DLS-2019** [arthur-e/Wicket#152]
The ESRI ArcGIS JavaScript API demo (https://arthur-e.github.io/Wicket/sandbox-arcgis.html) is failing

![image](https://user-images.githubusercontent.com/47884705/106754153-4ad98000-6635-11eb-9324-cd4b46ae1c53.png)

**Comment by DLS-2019** [comment]
I tried to use wicket in an Angular app: 

const wkt = new Wkt.Wkt();
wkt.read("POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))");     
console.log(wkt.components);       //it works up to here

// but then fails on 
 wkt.toObject();

![image](https://user-images.githubusercontent.com/47884705/106863632-790c9d80-66d1-11eb-9ed4-c970c3487ac2.png)

I noticed that the arcgis.html demo code uses  wkt.toObject(**config**); 

            config = {
                spatialReference: {
                    wkid: 4326 // WGS84 unprojected
                },
                editable: editable
            };
            obj = wkt.toObject(config); // Make an object

But wkt.toObject() is expecting 0 arguments....... it also results in the error above.

**Comment by arthur-e** [comment]
Thanks, @DLS-2019. I don't think the ArcGIS module in Wicket has been updated in a few years now, and the ArcGIS Javascript extension has likely made some breaking changes since then. See related issue #90.

**Comment by DLS-2019** [comment]
Thank you for the feedback @arthur-e  - I switched to using the TerraFormer plugin
