### ISSUE TITLE
Add to bower index?

### ISSUE THREAD

**Issue by arthur-e** [arthur-e/Wicket#46]
This was suggested by someone. I don't have enough information at the present time.

**Comment by svycka** [comment]
+1

**Comment by arthur-e** [comment]
I added Wicket to the Bower index with:
```
bower register Wicket git://github.com/arthur-e/Wicket.git
```

However, when I call `bower info Wicket` I am seeing:
```
bower not-cached    git://github.com/arthur-e/Wicket.git#*
bower resolve       git://github.com/arthur-e/Wicket.git#*
bower checkout      Wicket#master
bower resolved      git://github.com/arthur-e/Wicket.git#900e290bea

{
  name: 'Wicket',
  main: [
    'wicket.js',
    'wicket-arcgis.js',
    'wicket-gmap3.js',
    'wicket-leaflet.js'
  ],
  ignore: [
    'doc/*',
    'tests/*'
  ],
  devDependencies: {
    'uglify-js': '2.4.x'
  },
  homepage: 'https://github.com/arthur-e/Wicket'
}

No versions available.
```

We have several versions available as tagged releases and tags are on GitHub. Any idea what's wrong?

**Comment by svenlaater** [comment]
The issue might lie in your package versioning. Bower expects You to use [Semver](https://github.com/npm/node-semver) syntax e.g. x.x.x.

**Comment by KoenDierckx** [comment]
Sven is correct, use  MAJOR.MINOR.PATCH, I think it does not work now, because the PATCH part is mandatory.
I also noticed the bower.json file has version 1.2, within the v1.3 tag. So don't forget to bump the version in the bower.json before creating a new tag. 
Thanks in advance !

**Comment by krisd** [comment]
+1

**Comment by steveoh** [comment]
```λ bower install Wicket --save
bower not-cached    git://github.com/arthur-e/Wicket.git#*
bower resolve       git://github.com/arthur-e/Wicket.git#*
bower checkout      Wicket#master
bower resolved      git://github.com/arthur-e/Wicket.git#8b7c4e5ed6
bower install       Wicket#8b7c4e5ed6

Wicket#8b7c4e5ed6 src\Wicket
```

Seems to be working and can be closed.

ps: your npm package is out of date also.

**Comment by joostvenema** [comment]
+1

I'm using a custom resolver, which requires Semver. Please create version `1.3.1` and I'm happy :-)

https://www.jfrog.com/jira/browse/RTFACT-8187

**Comment by deeg** [comment]
@arthur-e, any chance you will update your versions so bower will work with something besides * or a commit hash.

It would be nice to be able to load the latest stable version by version number. If you still need help please let me know, more than happy to help.

**Comment by arthur-e** [comment]
I need to confirm that GitHub's automatic releases will still work if I re-tag all the versions with semantic version numbers, dropping the "v" that was prepended long ago at GitHub's suggestion. Hope to get back to you soon about this.

**Comment by arthur-e** [comment]
Pushed version 1.3.1, and tag name with semantic versioning, to GitHub.
