### ISSUE TITLE
Error: this.construct is undefined

### ISSUE THREAD

**Issue by chk1** [arthur-e/Wicket#63]
I always get this error message when using the method `toObject()`: 

In Firefox: `Error: this.construct is undefined`
In Chrome: `Uncaught TypeError: Cannot read property 'polygon' of undefined`

The line referenced in both cases is `wicket.js` 237 (tried v1.2 and latest): 
https://github.com/arthur-e/Wicket/blob/master/wicket.js#L237
` var obj = this.construct[this.type].call(this, config);`

This is the code I used:
```HTML
<!DOCTYPE HTML>
<html>
<script src="bower_components/Wicket/wicket.js"></script> 
<script type="text/javascript">
	var wkt = new Wkt.Wkt();
	wkt.read("POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))");
	console.log(wkt.toObject());
</script>
</html>
```

The examples on your website work without issues. Am I doing something wrong?

**Comment by chk1** [comment]
I just found `toJSON()` which works for my purposes

**Comment by arthur-e** [comment]
From your HTML example, it seems you didn't include `wicket-leaflet. js`, which is required for `Wkt.Wkt` instances to know how to construct Leaflet objects. If you load that file, then `construct()` should work just fine.

**Comment by SadafZohra** [comment]
Same issue because I didn't included wkt-gmap3.js earlier.

**Comment by krejko** [comment]
I also had this issue and realized another solution is to only import the plug-in file that's needed - in my case, that was the wicket-leaflet.js. This plugin file requires the wicket.js file so importing both was not necessary.

**Comment by tcjcodes** [comment]
In my React / next project trying to use `.fromObject()` I got the same error about `deconstruct` being undefined.
I just added this to the top of the file:

`import 'wicket/wicket-gmap3';`
