### ISSUE TITLE
Esri JS API - Wicket generates lat/long instead of web mercator coords for point features

### ISSUE THREAD

**Issue by PaulAngelino** [arthur-e/Wicket#70]
I'm testing your library with a co-worker using the Esri JavsScript API.  We allow the user to draw on the map and then we save to a database by passing the WKT generated by Wicket.  We use the following code to convert the Esri geometry to WKT:

wkt.fromObject(geometry);
var geodata = wkt.write();

It seems that when we draw point features on the map, the coordinates generated by Wicket in the WKT come back in lat/long coordinates instead of meters (we're drawing on a typical basemap in web mercator).  When we examine the spatial reference object of the point geometry it looks like this:

 {wkid: 102100, latestWkid: 3857}

This is consistent with what we see on line and polygon geometries that we draw, and indeed Wicket generates the WKT properly for those feature types using coordinates in meters, but for points it is converting to lat/long.

Please let me know: are we doing something wrong, or is there a problem with the library?

**Comment by arthur-e** [comment]
Hi @PaulAngelino, I should first mention that Wicket has only been tested with decimal degrees and I have no experience using WKT with coordinates in meters (e.g., with UTM projections). I'm also not very familiar with the ESRI JavaScript API.

If you're drawing in Web Mercator, the coordinates should be in decimal degrees. It sounds like you want your WKT coordinates to be in meters; is that correct? Or you merely want them to be consistent between point, line, and polygon features? The spatial reference object your provided does not mean anything to me, I'm afraid.

Maybe someone more experienced with the ESRI JavaScript API can comment?

**Comment by PaulAngelino** [comment]
Thanks for your reply @arthur-e.  The coordinates that the Esri JS API gives me are in meters.  I guess the most important thing here is consistency, yes.   We'd like all of our feature coordinates to remain in meters.  I dug into this with a colleague and I think we discovered where the problem lies.  I see that in the deconstruct function of your wicket-arcgis.js file, you reference obj.getLongitude() and obj.getLatitude() for point features instead of just referencing the x and y properties of the Esri Point object.  The getLatitude() and getLongitude() methods return decimal degrees whereas the x and y properties simply return the coordinates in whatever units the map is using (meters in my case).  It looks like for all the other feature types you just work with the raw rings, coordinate pairs, etc., which is why no conversion between meters and decimal degrees occurs with these other feature types.

My colleagues and I will fork this, make the change and test it.  Then we'll send you a pull request in case you want to merge it in.  Let me know if anything doesn't make sense in my explanation here.

**Comment by arthur-e** [comment]
Sounds good! I look forward to your pull request.

**Comment by steveoh** [comment]
this should be closed with 1b39f91e918aaf5921a1bcde6f39562bb628fada

**Comment by arthur-e** [comment]
By George, you're right!

**Comment by PaulAngelino** [comment]
Glad we could contribute!

- Paul
