### ISSUE TITLE
Can not render correctly a Polygon that used to render a couple of months ago

### ISSUE THREAD

**Issue by csavvakos** [arthur-e/Wicket#73]
Hi,

I have this collection of [Polygons](https://gist.github.com/csavvakos/96ffba3c3a2bf6d5e71b) which used to render correctly, but no longer does. It should look like a hand fan. I get a straight line instead.

**Comment by arthur-e** [comment]
Hi @csavvakos. Please provide more information. Are you using a specific release or the bleeding-edge of the repository? Have you upgraded since this rendered correctly? What were you using before?

**Comment by csavvakos** [comment]
Hi,

I've been always using the Google Maps API online demo. So I can not give you more information about a specific version. The last time I used it and worked correctly was at July 8, if this is of any help.

**Comment by arthur-e** [comment]
Probably related to #33. If so, a partial fix was implemented in 1.3.2.
