### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by kennynaoh** [arthur-e/Wicket#82]
Hello @arthur-e ,
I am the member in [cdnjs](https://github.com/cdnjs/cdnjs) project
We want to host this library.
But there are some version problems.
The latest git tag version is v1.3, but the latest version in ```packe.json``` is v1.1.0.
Please confirm this.
Thanks.

https://github.com/cdnjs/cdnjs/issues/6746

**Comment by arthur-e** [comment]
Hi @kennynaoh ,

I'm unfamiliar with `packe.json` and I don't believe that file is in the repository. Is this something that is automatically generated by some external framework? Our `package.json` and `bower.json` files both have a tagged version of 1.3.

Thanks,
Arthur

**Comment by arthur-e** [comment]
Latest version now 1.3.1.

**Comment by kennynaoh** [comment]
@arthur-e 
Thanks.
Also maybe you should publish the latest version on npm.

**Comment by arthur-e** [comment]
Updated on npm. Thanks!
