### ISSUE TITLE
please remove for-in loops 

### ISSUE THREAD

**Issue by Montago** [arthur-e/Wicket#83]
I had to remove about 10 for-in loops in both Wicket.js and Wicket.gmap.js in order to make it function properly. 

For-In has the side effect that it also iterate prototype functions on Array's - even though safe measure has been put in place : hasOwnProperty checks, it can still fail !

there are several alternatives which is better code:

eg:
**MDM / ES6**
Array.forEach(function (obj) {  ...  })

**shortcut for-loop**
for(var i=0, obj; obj = arr[i] ; i++)

**high performance:**
var i = arr.length
do{
   var obj = arr[i]
}while(--i)

**Comment by arthur-e** [comment]
Could you provide some more details on your implementation? I ask so that I can reproduce the problem you're having. In what framework/ browser do these 10 `for-in` loops cause Wicket to not work as expected?

As always, a Pull Request that passes the tests is appreciated.

**Comment by amenadiel** [comment]
Given a valid object, you don't know if its properties are in turn other objects (which you'd need to traverse using Object.keys) or arrays (which are safe to traverse with the methods you suggested). 

As valid geojson can be a an object containing an array of objects with different depths, replacing for..in would need more type checks, which is even less performant.

**Comment by Montago** [comment]
I guess i was wrong... 

the problem i tried to solve was #81  but failed to do so. 

I see that you use for..in to function with Arrays as well as JSON - and since you use hasOwnProperty there shouldn't be a problem.. 

sorry about the fuzz
