### ISSUE TITLE
reverseInnerPolygons should be automatic...

### ISSUE THREAD

**Issue by Montago** [arthur-e/Wicket#84]
eg: POLYGON((10 10,10 20,20 20,20 10,10 10),(11 11,19 11,19 19,11 19,11 11))

any multi-dimmensional POLYGON is ALWAYS a polygon with holes and therefore the holes should always orient themselves correctly..

instead of flipping the direction without checking, the framework should align to spec
eg: config.holeIsCCW = true

then use a sign calculation to orient the holes accordingly 

eg:

```
this.polygonIsClockwise = function (coords)
		{
			/// <summary>Get the 'Sign' of a polygon (true=clockwise : false=counterclowise)</summary>
			/// <param name="coords" type="Array">Array of coordinates</param>
			/// <returns type="Boolean">true = clockwise</returns>

			var area = 0,
				j = null,
				i = 0;

			for (i = 0; i < coords.length; i++)
			{
				j = (i + 1) % coords.length;
				area += coords[i][0] * coords[j][1];
				area -= coords[j][0] * coords[i][1];
			}

			return area > 0;
		};
```

**Comment by Montago** [comment]
http://stackoverflow.com/questions/8139739/wkt-how-do-you-define-polygons-with-3-rings-2-holes

**Comment by Montago** [comment]
https://github.com/arthur-e/Wicket/pull/85

**Comment by arthur-e** [comment]
Please reference #33 going forward.
