### ISSUE TITLE
Freehand drawing

### ISSUE THREAD

**Issue by dshorthouse** [arthur-e/Wicket#97]
You're welcome to make use of this if you like: https://rawgit.com/dshorthouse/0afc690b83ed056f6762a96702c041e7/raw/190037de4152654a2e4b1e13394b40ba67249fd4/wkt.html

**Comment by arthur-e** [comment]
Thanks! But this seems more related to the sandbox, which merely demonstrates Wicket, rather than the Wicket library itself.
